[theme]
base                = "light"
primaryColor        = "#1c6660"
backgroundColor     = "#f4f7f7"
secondaryBackgroundColor = "#eaf0f0"
textColor           = "#13232a"
borderColor         = "#dde6e7"
font                = "'Atkinson Hyperlegible Next', sans-serif"
baseRadius          = "10px"

[client]
toolbarMode = "minimal"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
